apiVersion: batch/v1
kind: CronJob
metadata:
  name: publix-deal-finder
  namespace: default
spec:
  # Run every day at 8 AM (adjust timezone as needed)
  # Format: minute hour day-of-month month day-of-week
  schedule: "0 8 * * *"
  
  # Keep last 3 successful and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: publix-deal-finder
        spec:
          restartPolicy: OnFailure
          
          containers:
          - name: scraper
            image: your-registry/publix-scraper:latest  # Replace with your image
            imagePullPolicy: Always
            
            env:
            # Search for chicken deals (comma-separated for multiple items)
            - name: SEARCH_ITEMS
              value: "chicken"
            
            # Optional: Specific store number (leave empty for all stores)
            - name: STORE_NUMBER
              value: "0458"
            
            # Discord webhook URL from Secret
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: publix-scraper-secrets
                  key: discord-webhook-url
            
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            
            # Security context
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                - ALL
---
apiVersion: v1
kind: Secret
metadata:
  name: publix-scraper-secrets
  namespace: default
type: Opaque
stringData:
  # Replace with your actual Discord webhook URL
  discord-webhook-url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN"